no owasp zap scan

diff --git a/.github/workflows/secured-CICD.yml b/.github/workflows/secured-CICD.yml
--- a/.github/workflows/secured-CICD.yml
+++ b/.github/workflows/secured-CICD.yml
@@ -86,27 +86,14 @@ jobs:
         run: |
           docker compose up -d
           sleep 15  
-       # Step 4: Test the app with curl
-      - name: Test app accessibility
-        run: |
-          curl --fail http://web:8000 || (echo "App is not accessible!" && exit 1)
+#       # Step 4: Test the app with curl
+#      - name: Test app accessibility
+#        run: |
+#          curl --fail http://web:8000 || (echo "App is not accessible!" && exit 1)
 
-      # Step 5: Run OWASP ZAP Scan
-      - name: ZAP Scan
-        uses: zaproxy/action-full-scan@v0.7.0
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          target: http://localhost:8000
-#      - name: Run OWASP ZAP Baseline Scan
-#        uses: zaproxy/action-baseline@v0.5.0
+#      # Step 5: Run OWASP ZAP Scan
+#      - name: ZAP Scan
+#        uses: zaproxy/action-full-scan@v0.7.0
 #        with:
 #          token: ${{ secrets.GITHUB_TOKEN }}
 #          target: http://localhost:8000
-#          docker_name: zaproxy/zap-stable
-#          cmd_options: '-r zap-report.html'
-#
-#      - name: Upload ZAP Report
-#        uses: actions/upload-artifact@v3
-#        with:
-#          name: ZAP Report
-#          path: zap-report.html
